spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/server-iron
    username: sa
    password: '{cipher}'
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션
