spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb:3306/msa
    username: root
    password: '{cipher}83dec4bd65b7ec6fc5934bbb2a8c0576b32ff837e89ab3f0ed598a0967ee43bf'
  jpa:
    hibernate:
      ddl-auto: none
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션
