logging:
  file:
    name: logs/eureka.log
    max-size: 500MB
    max-history: 10
  level:
    root: info
    com.iron.eureka-server: debug

spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  instance:
    hostname: eureka-server
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: "*"