logging:
  file:
    name: logs/gateway-server.log
    max-size: 500MB
    max-history: 10
  level:
    root: info
    com.iron.gateway-server: debug

spring:
  config:
    import:
      - classpath:/config/datasource-docker.yml
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
      - id: rms
        uri: lb://RMS
        predicates:
          - Path=/rms/**
        filters:
          - RewritePath=/rms/(?<segment>.*), /$\{segment}

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka