logging:
  file:
    name: logs/rms-local3.log
    max-size: 500MB
    max-history: 10
  level:
    root: info
    org.hibernate.SQL: debug
#    org.hibernate.type: trace

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/server-iron
    username: sa
    password: '{cipher}'
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션

mybatis:
  mapper-locations: mybatis/mappers/*.xml

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true

token:
  expiration_time: 86400000
  secret: IRON0000

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka